### ISSUE TITLE
[BUG?] PDF fillable wont stay saved

### ISSUE THREAD

**Issue by Fyrexian** [p4535992/foundryvtt-inventory-plus#11]
**Module Version:** v0.16.2

**Before open any issue**
No console errors

**Describe the bug**
I downloaded this module to use the pdf fillable feature and it worked 2 weeks ago(?)-ish and saved the information. Now it doesn't, but it remembers the old info before this feature started to fail. 

**To Reproduce**
1. Copy actor id
2. edit pdf and put actor id into pdf code

**Expected behavior**
To save the fillable boxes

**Browser:**
 - Foundry

**Foundry Version:** 10.286

**Game System:** PF2e 4.2.3

**Additional context**
https://user-images.githubusercontent.com/47077661/194621590-bf811d0f-382d-4879-b8c2-cce8f2f6af3b.mp4

**Comment by Fyrexian** [comment]
![image](https://user-images.githubusercontent.com/47077661/194623341-7879b00c-34bc-409b-b1a0-a7ba698d310c.png)
Finally found a script error, but it only pops up once when opening a pdf for the first time

**Comment by iotech-fvtt** [comment]
Are you sure you have the right github repo? This Inventory+, not PDFoundry....

**Comment by Fyrexian** [comment]
ah weird, idk how I got to here. My bad.
