### ISSUE TITLE
Bulk Override

### ISSUE THREAD

**Issue by Orionox** [p4535992/foundryvtt-inventory-plus#12]
I use the bulk option from variant encumbrance and it would be nice if the different categories could override bulk separately from the weight. that way I could have a backpack that is 4 bulk regardless of what is put inside it. It would also be nice textend the limits of a category to include item#. That way I could make a "potion pouch" that can only hold 5 potions or something similiar.

**Comment by p4535992** [comment]
_I use the bulk option from variant encumbrance and it would be nice if the different categories could override bulk separately from the weight. that way I could have a backpack that is 4 bulk regardless of what is put inside it_

I have tried something for this ... but the combinations are so many i need some feedback...


_It would also be nice textend the limits of a category to include item#. That way I could make a "potion pouch" that can only hold 5 potions or something similiar._

Sorry i din't get you want a limitation based on the quantity not the weight ?

**Comment by Orionox** [comment]
I'd be glad to help anyway I can.

Also, yeah, I'm coming over from item collection because your module just
works better. That module has an option where you limit the total # of
items that can be placed in a bag. Like a quiver can hold 50 arrows and
doesn't care about weight only cares about # of arrows.

**Comment by p4535992** [comment]
Try out for 0.6.12 add some more icons for help to track this... but my head is spinning right now

**Comment by Orionox** [comment]
> Try out for 0.6.12 add some more icons for help to track this... but my head is spinning right now

You sir are a legend! everything looks phenomenal
