### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Orionox** [p4535992/foundryvtt-inventory-plus#13]
**Module Version:** v0.6.9

**Before open any issue**
![Screenshot 2022-10-08 094712](https://user-images.githubusercontent.com/20059838/194715974-7d9cc369-9839-446d-a13c-5afcb1a56596.jpg)

**Describe the bug**
dragging and droopping on certain spots duplicates the item instead of moving it. 

**To Reproduce**
1. Open inventory
2. drag item onto the edge of a category
3. drop item
4. item is duplicated

**Expected behavior**
Item should not be duplicated. 

**Foundry Version:** 
v10.287
**Game System:** 
5e v2.03

**Comment by p4535992** [comment]
They are warnings and they are caused from these other modules:
https://foundryvtt.com/packages/WhisperBox
https://foundryvtt.com/packages/5e-training
https://foundryvtt.com/packages/skill-customization-5e

**Comment by Orionox** [comment]
> They are warnings and they are caused from these other modules: https://foundryvtt.com/packages/WhisperBox https://foundryvtt.com/packages/5e-training https://foundryvtt.com/packages/skill-customization-5e

I am able to recreate the duplicate bug with these modules active
![Screenshot 2022-10-09 085153](https://user-images.githubusercontent.com/20059838/194763601-14f2db02-2ce7-4491-8bbc-d9cf9afcbd05.jpg)

**Comment by p4535992** [comment]
Did you replicate the behaviour with just inventory plus ?

**Comment by p4535992** [comment]
k i replicate the issue

**Comment by p4535992** [comment]
should be fixed with 0.6.10
