### ISSUE TITLE
[BUG] Duplication glitch persists. Tested in an empty world. 

### ISSUE THREAD

**Issue by Orionox** [p4535992/foundryvtt-inventory-plus#14]
**Module Version:** v0.6.9

**Before open any issue**
![Screenshot 2022-10-09 090210](https://user-images.githubusercontent.com/20059838/194764117-e3765ef5-aa5a-4259-bcbb-b305e0f88a8b.jpg)

**Describe the bug**
dragging and droopping on certain spots duplicates the item instead of moving it. 

**To Reproduce**
1. Open inventory
2. drag item onto the edge of a category
3. drop item
4. item is duplicated

**Expected behavior**
Item should not be duplicated. 

**Foundry Version:** 
v10.287
**Game System:** 
5e v2.03

**Comment by p4535992** [comment]
should be fixed with 0.6.10
