### ISSUE TITLE
Conflict with Monk's enhanced journal "Shop" feature

### ISSUE THREAD

**Issue by mflaherty97** [p4535992/foundryvtt-inventory-plus#16]
When using the shop feature of "Monk's Enhanced Journal," items that are purchased through the shop do not automatically appear on a character's sheet.

**Comment by ZBell** [comment]
Not sure if this is helpful, but this is the error I get when I try to drag an item from the shop as the GM to a player's inventory,
![Item_DropData](https://user-images.githubusercontent.com/4707545/204608929-da00875b-8f39-44e4-8713-50e584d3ed1a.PNG)
This is the error they get when they purchase the item themselves, it's actually a warning and not an error,
![Item_NotItem](https://user-images.githubusercontent.com/4707545/204610928-4cf95896-aa49-4972-b59b-6be32bd9dcb9.PNG)
In neither case does the item go to their inventory.  Please let me know if there's anything I can do to help, tests, etc.!

**Comment by p4535992** [comment]
Should be fixe dlet me know it

**Comment by mflaherty97** [comment]
It sure is fixed. Thank you so much. Can't wait to use this module now.

**Comment by ZBell** [comment]
Works for me too, shops and looting, sorry it took me so long to check.  Thanks for such a quick fix!
