### ISSUE TITLE
[BUG] Dragging spells causes them to be duplicated

### ISSUE THREAD

**Issue by Datedsandwich** [p4535992/foundryvtt-inventory-plus#21]
**Module Version:** v0.6.14

**Describe the bug**
On PC sheets specifically, drag and dropping spells to re-order them results in them being duplicated. This doesn't occur in version 0.6.13

Only console output is `DEBUG | inventory-plus | flagCategory=false && flagDisableDefaultCategories=false`. No errors.

**To Reproduce**
1. Open a PC character sheet in the D&D 5e system, and navigate to the spellbook.
2. Drag and drop a spell that is already on the sheet, to re-order it.
3. The spell is duplicated rather than being re-ordered.

**Expected behavior**
The spell should move position in the list, and not be duplicated. This works correctly in version 0.6.13.

**Screenshots**

**Browser:**
Foundry application.

**Foundry Version:** 
v10.290

**Game System:** 
D&D 5e v2.0.3

**Additional context**
This works correctly in version 0.6.13.

**Comment by p4535992** [comment]
Should be fixed with 0.6.16

**Comment by Datedsandwich** [comment]
Yep, can confirm!
