### ISSUE TITLE
[BUG] Inventory category names/titles not showing properly

### ISSUE THREAD

**Issue by WyntherKnight** [p4535992/foundryvtt-inventory-plus#28]
**Module Version:** v 0.6.22

**Describe the bug**
Inventory category names/titles not showing properly after updating DnD 5th Edition system to 2.1.1 

**Screenshots**
![screenshot](https://user-images.githubusercontent.com/66346903/211722772-e5df2236-0aaf-4bb8-a2ea-9805e1ddbb9f.png)

**Foundry Version:** 
Foundry V10.291

**Game System:** 
DnD 5th Edition V 2.1.1

**Additional context**
No other modules active except for Inventory+ and  libWrapper. Disabling all modules show inventory category names properly.

**Comment by airbreather** [comment]
Broken in foundryvtt/dnd5e@3c2ab2fe

A relevant comment from the original PR: https://github.com/foundryvtt/dnd5e/pull/1935#issuecomment-1328298162

**Comment by p4535992** [comment]
should be fixed
