### ISSUE TITLE
[BUG] Foundry v10 Broke it

### ISSUE THREAD

**Issue by shecrio** [p4535992/foundryvtt-inventory-plus#6]
**Module Version:** v0.5.22
It's likely you already know of this but just to be on the safe side.

**Describe the bug**
Loading it in Foundry v10.284, dnd5e 2.0.2, Inventory+ throws an error followed by libWrapper throwing an error.
Even tested it in a world with just Inventory+ and libwrapper, no other modules just to be sure.

foundry.js:58303 Inventory+: Error detected in module. It is likely this module has not been updated for FVTT Version 10. (See JS Console)
fetch @ foundry.js:58303
notify @ foundry.js:58230
error @ foundry.js:58266
🎁_ui @ libWrapper-notifications.js:74
🎁ui @ libWrapper-notifications.js:82
(anonymous) @ listeners.js:27
C @ listeners.js:51
j @ listeners.js:67

module.js:407 Uncaught (in promise) LibWrapperPackageError: Error detected in module Inventory+. It is likely this module has not been updated for FVTT Version 10.

This is *not* a libWrapper bug.

Find information about this module here: https://github.com/p4535992/inventory-plus
Report this issue here: https://github.com/p4535992/inventory-plus/issues

== Technical Details:
Detected by libWrapper.
Package ID= inventory-plus
Error= Could not find target 'game.dnd5e.applications.ActorSheet5eCharacter.prototype.getData': Could not find scope 'ActorSheet5eCharacter'.

[Detected 1 package: inventory-plus]
    at ae (libWrapper-api.js:142)
    at se (libWrapper-api.js:152)
    at Function.🎁register [as register] (libWrapper-api.js:525)
    at readyHooks (module.js:34)
    at Object.fn (main.js:53)
    at Function.#call (foundry.js:688)
    at Function.callAll (foundry.js:645)
    at Game.setupGame (foundry.js:7769)
    at async Game._initializeGameView (foundry.js:8820)
    at async Game.initialize (foundry.js:7630)
LibWrapperError @ libWrapper-base_errors.js:25
LibWrapperPackageError @ libWrapper-base_errors.js:181
ae @ libWrapper-api.js:142
se @ libWrapper-api.js:152
🎁register @ libWrapper-api.js:525
readyHooks @ module.js:34
(anonymous) @ main.js:53
#call @ foundry.js:688
callAll @ foundry.js:645
setupGame @ foundry.js:7769
async function (async)
setupGame @ foundry.js:7728
_initializeGameView @ foundry.js:8820
_initializeView @ foundry.js:8796
initialize @ foundry.js:7630
async function (async)
initialize @ foundry.js:7621
🎁call_wrapped @ libWrapper-wrapper.js:511
🎁libWrapperInit @ libWrapper-api.js:796
async function (async)
🎁libWrapperInit @ libWrapper-api.js:786
🎁Game.prototype.initialize#0 @ libWrapper-wrapper.js:187
window.addEventListener.once @ foundry.js:78537
async function (async)
window.addEventListener.once @ foundry.js:78536

**Comment by p4535992** [comment]
this week end i was busy with others module, maybe the next week i'll find the time.

**Comment by p4535992** [comment]
So i prepared and released a version 10 of the module, but not find the time to fully testing for anyone interested.
