### ISSUE TITLE
[BUG] Can't install version 0.6.2

### ISSUE THREAD

**Issue by gantonaci** [p4535992/foundryvtt-inventory-plus#9]
**Module Version:** v0.6.2

**Describe the bug**
I uninstalled the module and tried to reinstall.
I get an error with the following message in the log

```
Errors were encountered while installing the package. Consult your console log (F12) for details.
fetch @ foundry.js:58526
setup.js:141 [inventory-plus] Metadata validation failed for module "inventory-plus": The file "languages/pt-BR.json" included by module inventory-plus does not exist
#logPackageWarnings @ setup.js:141
```
Maybe it is case sensitive. In the folders the file name is "pt-br.json" and in the manifest "pt-BR.json".

**Foundry Version:** 
v10

**Comment by p4535992** [comment]
should be fixed with 0.6.3 ty for point this out.

**Comment by gantonaci** [comment]
Np.
Thanks for taking the development of this module!

**Comment by gantonaci** [comment]
I'm still getting the same error on 0.6.3. :-(

**Comment by p4535992** [comment]
try out version 0.6.4...  :(

**Comment by gantonaci** [comment]
Still no deal.
I'm still getting the same error.

**Comment by rodrigosinistro** [comment]
Hi

I have the same issue.

Thanks

![Issue](https://user-images.githubusercontent.com/80776011/193727438-8d8badc6-68ec-4872-b418-227a4e73719a.png)

**Comment by gantonaci** [comment]
v0.6.6 installed nicely.
Thanks!
